use_frameworks!

platform :ios, '11.0'

target 'BaseViewController_Example' do
  pod 'BaseViewController', :path => '../'

  target 'BaseViewController_Tests' do
    inherit! :search_paths

    
  end
end
